# https://bcrypt-generator.com/ 
# password values need to be decoded with base64 & then use above url to validate 
# DO NOT APPLY THIS file directly as it updates existing data comes with installation. you may edit & add data fields accordingly.
kind: Secret
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  admin.password: YTIucklJTHpUVlZNQS9GU2xwNnhmOWVhLjR3YVhIbWkK
  accounts.readuser.password: YTIucklJTHpUVlZNQS9GU2xwNnhmOWVhLjR3YVhIbWkK
  accounts.test-user1.password: YTIucklJTHpUVlZNQS9GU2xwNnhmOWVhLjR3YVhIbWkK
  accounts.test-user2.password: YTIucklJTHpUVlZNQS9GU2xwNnhmOWVhLjR3YVhIbWkK